node_name: "r720-vm"
hardware_desc: "Dell PowerEdge R720 · 2× Intel Xeon E5-2690 v2 (IvyBridge-EP) · 96 GB DDR3 ECC"
specs:
  cores: 16
  peak_mips: 120000
  max_mem_bw_gbps: 59.7
ipmi:
  host: "192.168.68.98"
  user: "root"
  pass: "Legocity2019$"
