services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: hqud-victoriametrics
    ports:
      - "127.0.0.1:8428:8428"
    networks:
      - hqud_net
    restart: unless-stopped
    command:
      - "--storageDataPath=/victoria-metrics-data"
      - "--retentionPeriod=1y"
    volumes:
      - ./data/tsdb:/victoria-metrics-data

networks:
  hqud_net:
    name: hqud_net
    driver: bridge

volumes:
  hqud_vm_data:
