import { DatasheetCard } from '../components/DatasheetCard';
import type { MetricsState, SystemConfig } from '../types';
import { Download, Cpu, HardDrive, Server } from 'lucide-preact';
import { formatMetric, formatUptime } from '../utils/formatters';

interface Props {
  metrics: MetricsState;
  systemConfig: SystemConfig | null;
}

function generateAuditReport(metrics: MetricsState, config: SystemConfig | null) {
  const now = new Date().toISOString().split('T')[0];
  const nodeName = config?.node_name ?? 'Unknown';
  const hwDesc = config?.hardware_desc ?? 'Unknown';
  const cores = config?.specs.cores ?? 0;
  const peakMips = config?.specs.peak_mips ?? 0;
  const memBw = config?.specs.max_mem_bw_gbps ?? 0;

  const html = `<!DOCTYPE html>
<html><head><title>HQUD Audit Report - ${now}</title>
<style>
  body { font-family: 'Inter', 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1e293b; }
  h2 { border-bottom: 2px solid #0d9488; padding-bottom: 8px; }
  h3 { color: #334155; margin-top: 24px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { text-align: left; padding: 8px 12px; border: 1px solid #e2e8f0; font-size: 14px; }
  th { background: #f1f5f9; font-weight: 600; }
  td { font-family: 'Space Grotesk', monospace; }
  .meta { color: #64748b; font-size: 12px; }
</style></head><body>
<h2>HQUD Quantitative Audit Report — ${now}</h2>
<p class="meta">Auto-generated by HQUD Foundry v2.6.1</p>

<h3>System Information</h3>
<table>
  <tr><th>Node</th><td>${nodeName}</td></tr>
  <tr><th>Hardware</th><td>${hwDesc}</td></tr>
  <tr><th>Cores</th><td>${cores}</td></tr>
  <tr><th>Peak Throughput</th><td>${peakMips.toLocaleString()} MIPS</td></tr>
  <tr><th>Memory Bandwidth</th><td>${memBw} GB/s</td></tr>
  <tr><th>Uptime</th><td>${formatUptime(metrics.uptimeSeconds)}</td></tr>
</table>

<h3>Architectural Performance Summary</h3>
<table>
  <tr><th>Metric</th><th>Value</th><th>Unit</th></tr>
  <tr><td>Active Power</td><td>${formatMetric(metrics.powerW)}</td><td>W</td></tr>
  <tr><td>CPU Efficiency</td><td>${formatMetric(metrics.ipsPerW / 1e6)}</td><td>M IPS/W</td></tr>
  <tr><td>CPI</td><td>${formatMetric(metrics.cpi)}</td><td>cycles/instr</td></tr>
  <tr><td>AMAT</td><td>${formatMetric(metrics.amat)}</td><td>cycles</td></tr>
  <tr><td>NUMA Miss Rate</td><td>${formatMetric(metrics.numaMiss)}</td><td>%</td></tr>
  <tr><td>Cache Miss Rate</td><td>${formatMetric(metrics.cacheMiss)}</td><td>%</td></tr>
  <tr><td>TCP Retransmits</td><td>${formatMetric(metrics.tcpRetrans)}</td><td>/s</td></tr>
</table>
</body></html>`;

  const w = window.open('', '_blank');
  if (w) {
    w.document.write(html);
    w.document.close();
    setTimeout(() => w.print(), 500);
  }
}

export function Overview({ metrics, systemConfig }: Props) {
  return (
    <div className="flex flex-col h-full">
      <header className="bg-slate-900 border-b border-slate-800 px-4 md:px-8 py-4 flex justify-between items-center shrink-0">
        <div>
           <h2 className="text-sm md:text-lg font-semibold tracking-wider text-slate-300 uppercase line-clamp-1">
             Executive Overview
           </h2>
           <div className="text-[10px] font-mono text-slate-500 mt-1 uppercase tracking-widest hidden md:block">
             Real-time Performance Telemetry
           </div>
        </div>
        
        <button 
          onClick={() => generateAuditReport(metrics, systemConfig)}
          className="flex items-center gap-2 px-3 py-1.5 bg-transparent border border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800 hover:border-slate-500 transition-colors rounded-sm text-xs font-semibold tracking-wide">
          <Download size={14} />
          <span className="hidden md:inline">Export Audit Report (PDF)</span>
          <span className="inline md:hidden">PDF</span>
        </button>
      </header>

      <div className="p-4 md:p-8 flex-1 flex flex-col gap-6 w-full max-w-[1600px] mx-auto overflow-y-auto">
        <div>
          <h3 className="text-slate-400 font-mono uppercase tracking-widest text-xs mb-3">Core Datasheets</h3>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3 md:gap-4">
             <DatasheetCard title="ACTIVE POWER" value={formatMetric(metrics.powerW)} unit="W" footer="Total Package Draw" />
             <DatasheetCard title="CPU EFFICIENCY" value={formatMetric(metrics.ipsPerW / 1e6)} unit="M IPS/W" footer="Instr. per Watt" valueColor="text-teal-400" />
             <DatasheetCard title="MEMORY AMAT" value={formatMetric(metrics.amat)} unit="cyc" footer="Avg Mem Access Time" />
             <DatasheetCard title="NUMA MISS RATE" value={formatMetric(metrics.numaMiss)} unit="%" footer="Cross-node Fetches" />
             
             {/* v2.6.1: Strict check for TCP Bindings */}
             <div className="bg-slate-800 border border-slate-700 p-4">
               <div className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-1">TCP RETRANSMITS</div>
               <div className="text-4xl font-mono text-white">
                 {metrics.tcpRetrans !== undefined && metrics.tcpRetrans !== null ? formatMetric(metrics.tcpRetrans) : '-'}
                 <span className="text-sm text-slate-400 ml-1">/s</span>
               </div>
               <div className="text-[9px] text-slate-500 mt-2">Network Reliability</div>
             </div>

             <DatasheetCard title="SYSTEM UPTIME" value={formatUptime(metrics.uptimeSeconds)} unit="" footer="Dependability" valueColor="text-teal-400" />
          </div>
        </div>

        <div>
          <h3 className="text-slate-400 font-mono uppercase tracking-widest text-xs mb-3">System Configuration Metadata</h3>
          <div className="bg-slate-800 border border-slate-700 p-4 md:p-6 text-slate-300">
            {systemConfig ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4">
                <ConfigRow icon={<Server size={14} className="text-slate-500" />} label="NODE NAME" value={systemConfig.node_name || '—'} />
                <ConfigRow icon={<Cpu size={14} className="text-slate-500" />} label="HARDWARE" value={systemConfig.hardware_desc || '—'} />
                <ConfigRow icon={<Cpu size={14} className="text-slate-500" />} label="CORES" value={`${systemConfig.specs.cores} Cores`} />
                <ConfigRow icon={<HardDrive size={14} className="text-slate-500" />} label="PEAK THROUGHPUT" value={`${systemConfig.specs.peak_mips.toLocaleString()} MIPS`} />
                <ConfigRow icon={<HardDrive size={14} className="text-slate-500" />} label="MEMORY BANDWIDTH" value={`${systemConfig.specs.max_mem_bw_gbps} GB/s`} />
              </div>
            ) : (
              <div className="text-slate-500 font-mono text-xs animate-pulse">Fetching hardware configuration from /api/hardware...</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function ConfigRow({ icon, label, value }: { icon: any; label: string; value: string }) {
  return (
    <div className="flex items-center gap-3 border-b border-slate-700/50 pb-3">
      {icon}
      <div className="flex-1">
        <div className="text-[9px] md:text-[10px] text-slate-500 uppercase tracking-widest font-semibold">{label}</div>
        <div className="text-sm md:text-base text-slate-200 font-mono">{value}</div>
      </div>
    </div>
  );
}
