// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadNet_tcp returns the embedded CollectionSpec for net_tcp.
func loadNet_tcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Net_tcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load net_tcp: %w", err)
	}

	return spec, err
}

// loadNet_tcpObjects loads net_tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*net_tcpObjects
//	*net_tcpPrograms
//	*net_tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNet_tcpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNet_tcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// net_tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_tcpSpecs struct {
	net_tcpProgramSpecs
	net_tcpMapSpecs
	net_tcpVariableSpecs
}

// net_tcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_tcpProgramSpecs struct {
	TcpRetransmitSkb *ebpf.ProgramSpec `ebpf:"tcp_retransmit_skb"`
}

// net_tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_tcpMapSpecs struct {
	TcpRetransmitCount *ebpf.MapSpec `ebpf:"tcp_retransmit_count"`
}

// net_tcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_tcpVariableSpecs struct {
}

// net_tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNet_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_tcpObjects struct {
	net_tcpPrograms
	net_tcpMaps
	net_tcpVariables
}

func (o *net_tcpObjects) Close() error {
	return _Net_tcpClose(
		&o.net_tcpPrograms,
		&o.net_tcpMaps,
	)
}

// net_tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNet_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_tcpMaps struct {
	TcpRetransmitCount *ebpf.Map `ebpf:"tcp_retransmit_count"`
}

func (m *net_tcpMaps) Close() error {
	return _Net_tcpClose(
		m.TcpRetransmitCount,
	)
}

// net_tcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNet_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_tcpVariables struct {
}

// net_tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNet_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_tcpPrograms struct {
	TcpRetransmitSkb *ebpf.Program `ebpf:"tcp_retransmit_skb"`
}

func (p *net_tcpPrograms) Close() error {
	return _Net_tcpClose(
		p.TcpRetransmitSkb,
	)
}

func _Net_tcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed net_tcp_x86_bpfel.o
var _Net_tcpBytes []byte
